#!/usr/local/bin/python3
"""Block 2 mutations, using block 1's isolated-copy runner."""
from pathlib import Path
import sys

if __package__ in (None, ''):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts import mutation_check

MUTATIONS = [
    ('availability_uses_raw_timestamp', 'back/store.py', [('AND bar_end <= ?', 'AND ts_raw <= ?')],
     'tests.test_future_isolation.FutureIsolationTests.test_raw_at_t_is_invisible_but_bar_ending_at_t_changes_input_and_hash'),
    ('availability_plus_60_seconds', 'back/store.py',
     [('AND bar_end <= ?', 'AND bar_end < ?'),
      ("cutoff.isoformat(timespec='microseconds')", "(cutoff + timedelta(seconds=60)).isoformat(timespec='microseconds')")],
     'tests.test_future_isolation.FutureIsolationTests.test_available_bars_fractional_cutoff_rejects_plus_60_seconds_mutation'),
    ('availability_excludes_exact_endpoint', 'back/store.py',
     [("cutoff.isoformat(timespec='microseconds')", "(cutoff - timedelta(microseconds=1)).isoformat(timespec='microseconds')")],
     'tests.test_future_isolation.FutureIsolationTests.test_raw_at_t_is_invisible_but_bar_ending_at_t_changes_input_and_hash'),
    ('reference_reads_today_daily_close', 'back/replay.py',
     [("reference = self._reference(day, history[-1][0]['close'])",
       "reference = self._reference(day, self.store.db.execute('SELECT close FROM daily WHERE symbol=? AND day=?', (self.plan.symbol, day)).fetchone()[0])")],
     'tests.test_future_isolation.FutureIsolationTests.test_random_future_data_today_daily_and_unmatured_labels_never_change_predictions'),
    ('today_reads_full_day_bars', 'back/replay.py',
     [('visible = tuple(self.store.available_bars(day, t, self.plan.symbol))',
       'visible = tuple(self.store.available_bars(day, t.replace(hour=13, minute=30), self.plan.symbol))')],
     'tests.test_future_isolation.FutureIsolationTests.test_deleting_future_bars_and_today_daily_does_not_change_input_or_baselines'),
    ('minute_sample_minimum_relaxed_to_nine', 'back/replay.py', [('if len(samples) >= 10 else None', 'if len(samples) >= 9 else None')],
     'tests.test_replay.ReplayTests.test_minute_volume_uses_only_present_days_and_minimum_ten'),
    ('missing_minutes_filled_with_zero', 'back/replay.py',
     [('samples = [volumes[index] for _, volumes in history[-20:] if index in volumes]',
       'samples = [volumes.get(index, Fraction(0)) for _, volumes in history[-20:]]')],
     'tests.test_replay.ReplayTests.test_minute_volume_uses_only_present_days_and_minimum_ten'),
    ('zero_volume_samples_dropped', 'back/replay.py',
     [('samples = [volumes[index] for _, volumes in history[-20:] if index in volumes]',
       'samples = [volumes[index] for _, volumes in history[-20:] if index in volumes and volumes[index] > 0]')],
     'tests.test_replay.ReplayTests.test_zero_volume_is_present_and_zero_mean_is_null'),
    ('recent_limit_removed', 'back/replay.py', [('for bar in visible[-60:]:', 'for bar in visible:')],
     'tests.test_replay.ReplayTests.test_recent_is_same_day_at_most_60_and_no_gap_filling'),
    ('previous_day_mean_includes_itself', 'back/replay.py', [('history[i - 20:i]', 'history[i - 19:i + 1]')],
     'tests.test_replay.ReplayTests.test_f1_matches_hand_computed_state_canonical_json_and_hash'),
    ('unknown_reference_falls_back_to_previous_close', 'back/replay.py',
     [("if status['state'] == 'unknown':\n            return None", "if status['state'] == 'unknown':\n            return previous_close")],
     'tests.test_replay.ReplayTests.test_unknown_current_and_prior_reference_reject_no_silent_previous_close'),
    ('corporate_reference_ignored', 'back/replay.py',
     [("return status['event']['ref_price']", 'return previous_close')],
     'tests.test_replay.ReplayTests.test_event_reference_and_known_none_previous_close'),
    ('label_up_boundary_exclusive', 'back/replay.py', [('if end * 1000 >= start * (1000 + k):', 'if end * 1000 > start * (1000 + k):')],
     'tests.test_replay.ReplayTests.test_integer_labels_at_boundaries_from_original_price_strings'),
    ('label_down_boundary_exclusive', 'back/replay.py', [('if end * 1000 <= start * (1000 - k):', 'if end * 1000 < start * (1000 - k):')],
     'tests.test_replay.ReplayTests.test_integer_labels_at_boundaries_from_original_price_strings'),
    ('label_uses_binary_float', 'back/replay.py', [('start, end = exact(close_t), exact(close_end)', 'start, end = float(close_t), float(close_end)')],
     'tests.test_replay.ReplayTests.test_integer_labels_at_boundaries_from_original_price_strings'),
    ('outcome_looks_one_minute_too_far', 'back/replay.py', [('end = t + timedelta(minutes=30)', 'end = t + timedelta(minutes=31)')],
     'tests.test_replay.ReplayTests.test_outcome_ends_at_30_minutes_and_never_uses_next_minute'),
    ('auction_requirement_removed', 'back/replay.py',
     [("if t.time() == time(13) and local_time(bars[-1]['ts_raw']).time() != time(13, 30):", 'if False:')],
     'tests.test_replay.ReplayTests.test_1300_requires_actual_1330_auction_even_if_1325_is_fresh_enough'),
    ('current_price_freshness_relaxed', 'back/replay.py',
     [("local_time(visible[-1]['bar_end']) < t - timedelta(minutes=5)", "local_time(visible[-1]['bar_end']) < t - timedelta(minutes=6)")],
     'tests.test_replay.ReplayTests.test_current_price_freshness_five_minutes_inclusive_and_no_bar'),
    ('majority_maturity_gate_removed', 'back/baselines.py', [('if t + timedelta(minutes=30) > cutoff:', 'if False:')],
     'tests.test_baselines.BaselineTests.test_majority_maturity_boundary_and_pending_poison_label_ignored'),
    ('majority_cohort_gate_removed', 'back/baselines.py', [('if not record.predictable or not record.scorable:', 'if False:')],
     'tests.test_baselines.BaselineTests.test_majority_cohort_excludes_unpredictable_unscorable_and_warmup'),
    ('majority_dev_scope_removed', 'back/baselines.py', [("if plan.split_of(t.date().isoformat()) != 'dev':", 'if False:')],
     'tests.test_baselines.BaselineTests.test_majority_cohort_excludes_unpredictable_unscorable_and_warmup'),
    ('majority_laplace_smoothing_removed', 'back/baselines.py', [('(counts[label] + 1) / denominator', 'counts[label] / denominator')],
     'tests.test_baselines.BaselineTests.test_majority_no_labels_flat_uniform_and_stable_ties'),
    ('momentum_first_close_instead_of_open', 'back/baselines.py',
     [("start = point.visible_bars[0]['open']", "start = point.visible_bars[0]['close']")],
     'tests.test_baselines.BaselineTests.test_momentum_first_point_uses_open_not_first_close'),
    ('momentum_start_freshness_relaxed', 'back/baselines.py',
     [("local_time(prior[-1]['bar_end']) < point.t - timedelta(minutes=35)",
       "local_time(prior[-1]['bar_end']) < point.t - timedelta(minutes=36)")],
     'tests.test_baselines.BaselineTests.test_momentum_uses_same_day_closed_start_and_five_minute_freshness'),
    ('reversal_becomes_momentum', 'back/baselines.py',
     [("{'up': 'down', 'flat': 'flat', 'down': 'up'}[answer]", "{'up': 'up', 'flat': 'flat', 'down': 'down'}[answer]")],
     'tests.test_baselines.BaselineTests.test_reversal_flat_and_both_directions_and_configured_threshold'),
    ('audit_labels_include_unpredictable_points', 'scripts/check_replay.py',
     [('if point.predictable and outcome.scorable:', 'if outcome.scorable:')],
     'tests.test_replay_audit.ReplayAuditTests.test_development_cohort_counts_and_no_holdout_traversal_or_output'),
    ('audit_traverses_holdout', 'scripts/check_replay.py', [("for t in replay.candidates('dev'):", "for t in replay.candidates('holdout'):")],
     'tests.test_replay_audit.ReplayAuditTests.test_development_cohort_counts_and_no_holdout_traversal_or_output'),
]


if __name__ == '__main__':
    mutation_check.MUTATIONS = MUTATIONS
    raise SystemExit(mutation_check.main())
