#!/usr/local/bin/python3
"""Score/report behavior mutations; isolated temporary copies, synthetic data only."""
from pathlib import Path
import sys

if __package__ in (None, ''):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts import mutation_check

S = 'tests.test_score.ScoreMathTests.'
R = 'tests.test_report.ReportTests.'
MUTATIONS = [
    ('significantly_worse_hidden', 'back/score.py',
     [('if brier_difference > 0 and ci95[0] > 0:', 'if False:')],
     S + 'test_conclusion_worse'),
    ('wilson_z_removed', 'back/score.py', [('z2 = Z95 * Z95', 'z2 = 0')],
     S + 'test_hand_calculated_accuracy_confusion_precision_recall_and_brier'),
    ('wilson_empty_invented', 'back/score.py', [('if n == 0:\n        return None', 'if n == 0:\n        return [0, 1]')],
     S + 'test_wilson_empty_extremes_known_values_and_invalid_counts'),
    ('confusion_transposed', 'back/score.py', [('matrix[point.truth][point.choice] += 1', 'matrix[point.choice][point.truth] += 1')],
     S + 'test_hand_calculated_accuracy_confusion_precision_recall_and_brier'),
    ('precision_uses_truth_denominator', 'back/score.py', [('tp / predicted if predicted else None', 'tp / actual if actual else None')],
     S + 'test_hand_calculated_accuracy_confusion_precision_recall_and_brier'),
    ('recall_uses_prediction_denominator', 'back/score.py', [('tp / actual if actual else None', 'tp / predicted if predicted else None')],
     S + 'test_hand_calculated_accuracy_confusion_precision_recall_and_brier'),
    ('brier_divided_by_three', 'back/score.py', [('                         for label in LABELS)\n', '                         for label in LABELS) / 3\n')],
     S + 'test_multiclass_brier_not_divided_by_classes_or_two'),
    ('bootstrap_uses_individual_points', 'back/score.py', [('grouped[t[:10]].append', 'grouped[t].append')],
     S + 'test_unequal_day_sizes_change_interval_and_all_points_stay_together'),
    ('bootstrap_averages_day_means', 'back/score.py',
     [('count = sum(block[0] for block in sampled)', 'count = len(sampled)'),
      ('math.fsum(block[1] for block in sampled) / count', 'math.fsum(block[1] / block[0] for block in sampled) / count'),
      ('sum(block[2] for block in sampled) / count', 'sum(block[2] / block[0] for block in sampled) / count')],
     S + 'test_unequal_day_sizes_change_interval_and_all_points_stay_together'),
    ('bootstrap_unpaired_methods', 'back/score.py',
     [('left.brier - right.brier', 'left.brier - baseline[sorted(baseline)[(sorted(baseline).index(t) + 1) % len(baseline)]].brier')],
     S + 'test_pairing_uses_same_draws_and_does_not_resample_methods_independently'),
    ('bootstrap_sign_reversed', 'back/score.py', [('left.brier - right.brier', 'right.brier - left.brier')],
     S + 'test_bootstrap_single_day_empty_and_percentile_interpolation'),
    ('bootstrap_repetitions_reduced', 'back/score.py', [('BOOTSTRAP_REPETITIONS = 2000', 'BOOTSTRAP_REPETITIONS = 200')],
     S + 'test_day_bootstrap_is_paired_point_weighted_fixed_seed_and_order_independent'),
    ('bootstrap_seed_changed', 'back/score.py', [('BOOTSTRAP_SEED = 20260927', 'BOOTSTRAP_SEED = 1')],
     S + 'test_day_bootstrap_is_paired_point_weighted_fixed_seed_and_order_independent'),
    ('percentile_drops_interpolation', 'back/score.py',
     [('ordered[low] + (ordered[high] - ordered[low]) * (position - low)', 'ordered[low]')],
     S + 'test_bootstrap_single_day_empty_and_percentile_interpolation'),
    ('coverage_cutoff_94_percent', 'back/score.py', [('common_n * 100 < eligible_n * 95', 'common_n * 100 < eligible_n * 94')],
     S + 'test_four_conclusion_sentences_and_touching_zero'),
    ('exactly_95_incorrectly_incomplete', 'back/score.py', [('common_n * 100 < eligible_n * 95', 'common_n * 100 <= eligible_n * 95')],
     S + 'test_four_conclusion_sentences_and_touching_zero'),
    ('touching_zero_declared_superior', 'back/score.py', [('ci95[1] < 0', 'ci95[1] <= 0')],
     S + 'test_four_conclusion_sentences_and_touching_zero'),
    ('primary_replaced_by_accuracy', 'back/score.py',
     [("conclusion(baseline, brier, bootstrap['brier_difference_ci95']", "conclusion(baseline, -accuracy, [-v for v in reversed(bootstrap['accuracy_difference_ci95'])]")],
     S + 'test_primary_brier_drives_conclusion_when_accuracy_is_worse'),
    ('comparison_uses_union', 'back/score.py', [('common.intersection_update(scored[method])', 'common.update(scored[method])')],
     R + 'test_own_metrics_coverage_and_comparison_use_different_correct_denominators'),
    ('coverage_includes_unscorable', 'back/score.py', [("'coverage': len(scored[method]) / len(eligible)", "'coverage': valid[method] / len(eligible)")],
     R + 'test_unpredictable_and_unscorable_answers_cannot_inflate_coverage'),
    ('ineligible_predictable_guard_removed', 'back/score.py', [('if not point.predictable:\n            continue', 'if False:\n            continue')],
     R + 'test_unpredictable_and_unscorable_answers_cannot_inflate_coverage'),
    ('prediction_input_guard_removed', 'back/score.py', [('if row[\'input_hash\'] != point.input_hash or row[\'input_json\'] != point.input_json:', 'if False:')],
     R + 'test_corrupt_input_probabilities_model_or_outcomes_do_not_inflate_results'),
    ('model_validation_removed', 'back/score.py', [("if row['model_reported'] is not None:", 'if False:')],
     R + 'test_corrupt_input_probabilities_model_or_outcomes_do_not_inflate_results'),
    ('outcome_guard_removed', 'back/score.py', [('if old is not None and (not outcome.scorable or', 'if False and (not outcome.scorable or')],
     R + 'test_corrupt_input_probabilities_model_or_outcomes_do_not_inflate_results'),
    ('latest_run_status_ignored', 'back/score.py', [("latest['status'] == 'complete' and not invalid[method]", 'True and not invalid[method]')],
     R + 'test_running_or_cancelled_latest_run_suppresses_conclusion_despite_answers'),
    ('partial_run_treated_as_full', 'back/score.py', [('(traversed or valid[method] == predictable)', 'True')],
     R + 'test_partial_smoke_not_complete_even_above_95_percent'),
    ('failure_attempts_replaced_by_missing', 'back/score.py', [("sum(run['n_fail'] for run in runs[method])", 'len(eligible) - len(scored[method])')],
     R + 'test_finished_failures_and_historical_retries_are_not_missing_counts'),
    ('baseline_selected_by_accuracy', 'back/score.py', [('development.scored[method][t].brier for t in development.common', '-development.scored[method][t].correct for t in development.common')],
     R + 'test_best_baseline_uses_brier_not_accuracy_fixed_tie_order'),
    ('baseline_selected_on_own_samples', 'back/score.py',
     [('development.scored[method][t].brier for t in development.common) / len(development.common)',
       'p.brier for p in development.scored[method].values()) / len(development.scored[method])')],
     R + 'test_baseline_selection_uses_same_development_intersection'),
    ('baseline_reselected_on_holdout', 'back/report.py', [('split_report(held, baseline, development_ready=ready)', 'split_report(held, best_development_baseline(held), development_ready=ready)')],
     R + 'test_holdout_keeps_development_winner_even_if_another_is_perfect_there'),
    ('unfinished_dev_ignored_on_holdout', 'back/report.py', [('development_ready=ready', 'development_ready=True')],
     R + 'test_unfinished_development_blocks_holdout_conclusion_after_reveal'),
    ('choice_hit_rate_uses_recall', 'back/score.py', [("hit_rate=values['precision']", "hit_rate=values['recall']")],
     S + 'test_descriptive_bias_and_choice_hit_rates_use_identical_samples'),
    ('bias_sign_reversed', 'back/score.py', [('(predicted - actual) / n', '(actual - predicted) / n')],
     S + 'test_descriptive_bias_and_choice_hit_rates_use_identical_samples'),
    ('score_reader_unlock_guard_removed', 'back/score.py', [("if split == 'holdout' and not holdout_revealed(store, row):", 'if False:')],
     R + 'test_score_reader_itself_rejects_locked_holdout_before_loading_plan'),
    ('report_unlock_guard_removed', 'back/report.py', [('if not holdout_revealed(store, row):', 'if False:')],
     R + 'test_locked_report_and_day_do_not_even_evaluate_holdout_and_views_do_not_reveal'),
    ('day_unlock_guard_removed', 'back/report.py', [("if access != 'allowed':", 'if False:')],
     R + 'test_locked_report_and_day_do_not_even_evaluate_holdout_and_views_do_not_reveal'),
    ('status_includes_hidden_runs', 'back/report.py', [("WHERE experiment_id=? AND split='dev' ORDER BY id", 'WHERE experiment_id=? ORDER BY id')],
     R + 'test_all_locked_exits_insensitive_to_hidden_predictions_labels_prices_and_run_counts'),
    ('labels_reveal_unlocks_everything', 'back/experiment.py', [("WHERE experiment_id=? AND what='all'\n", 'WHERE experiment_id=?\n')],
     R + 'test_labels_only_reveal_does_not_unlock_report_or_chart'),
    ('frozen_warning_removed', 'back/report.py', [("AND note='frozen_difference'\n", "AND note='not_a_warning'\n")],
     R + 'test_frozen_difference_warning_without_overwriting_or_leaking_prices'),
    ('warning_scope_includes_hidden_same_month', 'back/report.py', [('range_start<=? AND range_end>=?', 'substr(range_start,1,7)<=substr(?,1,7) AND range_end>=?')],
     R + 'test_hidden_only_fetch_warning_in_same_month_does_not_affect_report_or_status'),
    ('jev_partial_scope_marked_full', 'back/jevcast.py', [('int(times is None)', '1')],
     'tests.test_jev_runner.RunnerTests.test_persist_resume_and_duplicate_times_no_repeat_http'),
    ('baseline_scope_record_removed', 'scripts/run_dev.py', [("store.db.execute('INSERT INTO run_scopes VALUES (?,1)', (run_id,))", 'pass')],
     'tests.test_run_dev.RunDevTests.test_only_dev_methods_outcomes_and_report_and_restart_zero_http'),
    ('report_output_can_overwrite_database', 'scripts/report.py', [('if args.output and (args.output.resolve()', 'if False and (args.output.resolve()')],
     R + 'test_cli_is_readonly_has_no_reveal_switch_and_renders_both_formats'),
]

if __name__ == '__main__':
    mutation_check.MUTATIONS = MUTATIONS
    raise SystemExit(mutation_check.main())
